naver-api:
  endpoint: https://naveropenapi.apigw.ntruss.com/sentiment-analysis/v1/analyze
  api-key: YsGhPPnxNSuzAkPTwrGjOknlFzFCgDFN1eYQzIYx
  api-key-id: t7ho4lh6as

naver-papago:
  endpoint: https://naveropenapi.apigw.ntruss.com/nmt/v1/translation
  api-key: 2CiNUx3lwNdwHD4rtI7pm5zxZTjPlXNAQzAheXYE
  api-key-id: nshlfk46cj

naver-summary:
  endpoint: https://naveropenapi.apigw.ntruss.com/text-summary/v1/summarize
  api-key: rWxhuOwO4Nf5w360ASGSaBT8iuoYUa16WlRxQnEE
  api-key-id: qgsfydxfoa

karlo:
  url: https://api.kakaobrain.com/v2/inference/karlo/t2i
  key: 36f389847c38aeb1bc4fb2dc89c92a01


# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahwhew?characterEncoding=UTF-8
    username: root
    password: testㅈ[비리리릴릴sfffdff

# JWT
jwt:
  issuer: admin@spring.security.com
  secret_key: sesac-spring-boot-123456

# ASWS3
cloud:
  aws:
    s3:
      bucket: example-bucket-seeun
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIA55BXXA2BFGVUXJ7P
      secretKey: S3JL7vZsBHSM3kR4CBkOWVkP4KYcS2YOVOzz2iep